// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWYo9AzneeSl7IkUIGxhE03mMgCRrA4KY',
    appId: '1:138689734758:web:41dd5eec38f16ed6cfe5a7',
    messagingSenderId: '138689734758',
    projectId: 'my-todo-project98',
    authDomain: 'my-todo-project98.firebaseapp.com',
    storageBucket: 'my-todo-project98.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuHG2xqiaxfw3A_BseDwSZwQIAZTYLlwM',
    appId: '1:138689734758:android:fb33322446b80b8fcfe5a7',
    messagingSenderId: '138689734758',
    projectId: 'my-todo-project98',
    storageBucket: 'my-todo-project98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqeMps0WMQh7cyxl-nQNXNsqmluKdYqsg',
    appId: '1:138689734758:ios:1df77eba87e1998fcfe5a7',
    messagingSenderId: '138689734758',
    projectId: 'my-todo-project98',
    storageBucket: 'my-todo-project98.appspot.com',
    iosBundleId: 'com.example.myTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqeMps0WMQh7cyxl-nQNXNsqmluKdYqsg',
    appId: '1:138689734758:ios:9a968346629777e3cfe5a7',
    messagingSenderId: '138689734758',
    projectId: 'my-todo-project98',
    storageBucket: 'my-todo-project98.appspot.com',
    iosBundleId: 'com.example.myTodoApp.RunnerTests',
  );
}
